# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/aigc_tool.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15proto/aigc_tool.proto\"l\n\nChatApiReq\x12\x0f\n\x07userIds\x18\x01 \x01(\x05\x12\r\n\x05model\x18\x02 \x01(\t\x12\x13\n\x0b\x63ontentType\x18\x03 \x01(\x05\x12\x0e\n\x06\x61piKey\x18\x04 \x01(\t\x12\x19\n\x07\x63ontent\x18\x05 \x03(\x0b\x32\x08.Content\"d\n\nChatApiRes\x12\x16\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x08.RetCode\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x16\n\x04\x64\x61ta\x18\x03 \x03(\x0b\x32\x08.Content\x12\x15\n\x05usage\x18\x04 \x01(\x0b\x32\x06.Usage\"(\n\x07\x43ontent\x12\x0c\n\x04role\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"L\n\x05Usage\x12\x18\n\x10\x63ompletionTokens\x18\x01 \x01(\x05\x12\x14\n\x0cpromptTokens\x18\x02 \x01(\x05\x12\x13\n\x0btotalTokens\x18\x03 \x01(\x05*;\n\x07RetCode\x12\x0b\n\x07SUCCESS\x10\x00\x12\x11\n\rINVALID_PARAM\x10\x01\x12\x10\n\x0cINTERNAL_ERR\x10\x02\x32\x34\n\x0b\x41igcService\x12%\n\x07\x43hatApi\x12\x0b.ChatApiReq\x1a\x0b.ChatApiRes\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.aigc_tool_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RETCODE._serialized_start=357
  _RETCODE._serialized_end=416
  _CHATAPIREQ._serialized_start=25
  _CHATAPIREQ._serialized_end=133
  _CHATAPIRES._serialized_start=135
  _CHATAPIRES._serialized_end=235
  _CONTENT._serialized_start=237
  _CONTENT._serialized_end=277
  _USAGE._serialized_start=279
  _USAGE._serialized_end=355
  _AIGCSERVICE._serialized_start=418
  _AIGCSERVICE._serialized_end=470
# @@protoc_insertion_point(module_scope)
