# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import aigc_tool_pb2 as proto_dot_aigc__tool__pb2


class AigcServiceStub(object):
    """service 关键字定义提供的服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ChatApi = channel.unary_unary(
                '/AigcService/ChatApi',
                request_serializer=proto_dot_aigc__tool__pb2.ChatApiReq.SerializeToString,
                response_deserializer=proto_dot_aigc__tool__pb2.ChatApiRes.FromString,
                )


class AigcServiceServicer(object):
    """service 关键字定义提供的服务
    """

    def ChatApi(self, request, context):
        """定义一个调用chatgbt API的接口
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AigcServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ChatApi': grpc.unary_unary_rpc_method_handler(
                    servicer.ChatApi,
                    request_deserializer=proto_dot_aigc__tool__pb2.ChatApiReq.FromString,
                    response_serializer=proto_dot_aigc__tool__pb2.ChatApiRes.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'AigcService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AigcService(object):
    """service 关键字定义提供的服务
    """

    @staticmethod
    def ChatApi(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AigcService/ChatApi',
            proto_dot_aigc__tool__pb2.ChatApiReq.SerializeToString,
            proto_dot_aigc__tool__pb2.ChatApiRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
